<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun = rerun.strip.gsub /\s/, ' '
rerun_opts = rerun.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags 'not @wip'"
%>
default: --require features/support --require features/step_definitions <%= std_opts %> features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags 'not @wip'
assign_admin: --require features/support --require features/step_definitions features/assign_as_admin.feature
